### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by irl** [simonyiszk/csdr#8]
Hi,

The last release was a long time ago and there have been many commits since that release.

Are you planning to make one soon?

Thanks,

**Comment by ha7ilm** [comment]
Yes, I'll make one, and will use a <a href="https://github.com/simonyiszk/csdr/issues/9">soname</a> as well.

**Comment by irl** [comment]
Awesome thanks.

Got some issues in Debian with emscripten but working towards getting this packaged soon. Had many many requests for me to hurry up with openwebrx packaging, people are rather excited to have it in Debian.

**Comment by ha7ilm** [comment]
> Had many many requests for me to hurry up with openwebrx packaging, people are rather excited to have it in Debian.

Wow! Great! 

> Got some issues in Debian with emscripten but working towards getting this packaged soon.

Thank you for that!

**Comment by ha7ilm** [comment]
Ian, sorry for the delay. I know about some bugs in OpenWebRX and csdr that I think should be fixed, but I still need to find time for that.

**Comment by ckuethe** [comment]
Any word on making a release?

**Comment by ha7ilm** [comment]
Yeah, you're right. I managed to fix those bugs back in January. Before that, OpenWebRX hanged after a few hundreds of connection attempts (see https://github.com/simonyiszk/openwebrx/issues/42). Now that people have done some testing, it looks quite stable. I'd still have to do the SONAME thing that @irl asked for.

**Comment by ha7ilm** [comment]
Done, see v0.15 for both csdr and OpenWebRX.

**Comment by ha7ilm** [comment]
Note that the Makefile for `csdr` figures out compiler flags from cpuinfo to force some optimizations, so that the same binary won't run on all computers (if compiled with the default Makefile). I don't know much about how to make a package, but I think this needs to be worked around before, because I have already got some "opcode not found" errors when moving the binaries between PCs. On the other hand, building with `-O0` would also make things slower, especially the `fir_decimate_cc` routine needs the optimizations to make OpenWebRX fast.
